import spacy
from pprint import pprint

nlp = spacy.load('en_core_web_sm')

def get_stopwords_dict():

    stop_words = nlp.Defaults.stop_words

    pos_to_stop_words = {}

    for word in stop_words:
        pos = nlp(word)[0].pos_
        if pos in pos_to_stop_words:
            pos_to_stop_words[pos].append(word)
        else:
            pos_to_stop_words[pos] = [word]

    return pos_to_stop_words



if __name__ == "__main__":
    def main():
        d = get_stopwords_dict()
        print(sorted(d.keys()))
        pprint(d)
    main()

"""
['ADJ',
 'ADP',
 'ADV',
 'AUX',
 'CCONJ',
 'DET',
 'INTJ',
 'NOUN',
 'NUM',
 'PART',
 'PRON',
 'PUNCT',
 'SCONJ',
 'VERB']
{'ADJ': ['same',
         'few',
         'former',
         'full',
         'serious',
         'own',
         'empty',
         'such',
         'several',
         'latter',
         'various',
         'other',
         'least',
         'many',
         'whole',
         'top',
         'due',
         'whereafter',
         'last',
         'third'],
 'ADP': ['behind',
         'with',
         'below',
         'of',
         'through',
         'amongst',
         'at',
         'onto',
         'thru',
         'among',
         'throughout',
         'under',
         'into',
         'before',
         'beside',
         'against',
         'within',
         'per',
         'towards',
         'after',
         'without',
         'beyond',
         'from',
         'via',
         'in',
         'on',
         'as',
         'than',
         'during',
         'for',
         'toward',
         'until',
         'above',
         'across',
         'along',
         'between',
         'over',
         'by'],
 'ADV': ['together',
         'so',
         'therein',
         'next',
         'off',
         'meanwhile',
         'whereupon',
         'sometimes',
         'again',
         'rather',
         'enough',
         'thereby',
         'first',
         'too',
         'always',
         'either',
         'somehow',
         'very',
         'perhaps',
         'back',
         'down',
         'elsewhere',
         'latterly',
         'moreover',
         'formerly',
         'about',
         'sometime',
         'really',
         'once',
         'else',
         'anyhow',
         'also',
         'there',
         'most',
         'nowhere',
         'then',
         'up',
         'out',
         'further',
         'however',
         'yet',
         'namely',
         'afterwards',
         'already',
         'hereby',
         'thereupon',
         'still',
         'hence',
         'anyway',
         'even',
         'much',
         'thus',
         'never',
         'almost',
         'alone',
         'somewhere',
         'here',
         'more',
         'hereupon',
         'indeed',
         'now',
         'beforehand',
         'everywhere',
         'just',
         'anywhere',
         'often',
         'thereafter',
         'therefore',
         'nevertheless',
         'ever',
         'quite',
         'mostly',
         'around',
         'only',
         'otherwise',
         'less'],
 'AUX': ['might',
         'will',
         'being',
         '’d',
         'can',
         '’ll',
         'are',
         'was',
         "'ll",
         'ca',
         'could',
         'must',
         'would',
         "'re",
         'may',
         'were',
         "'s",
         'should',
         'be',
         'cannot',
         'am',
         'is',
         'been'],
 'CCONJ': ['but', 'or', 'and', 'nor', 'neither'],
 'DET': ['whose'],
 'INTJ': ['please', 'well', 'no'],
 'NOUN': ['part',
          'bottom',
          'whither',
          'side',
          'name',
          'thence',
          'amount',
          'whence',
          'yourselves',
          'noone',
          'front',
          'yours',
          'others',
          'none',
          'hers',
          '‘s',
          'ours',
          'herein'],
 'NUM': ['one',
         'twenty',
         'nine',
         'sixty',
         'ten',
         'five',
         'fifty',
         'forty',
         'n’t',
         'six',
         'three',
         'hundred',
         'eleven',
         'twelve',
         'fifteen',
         'four',
         'two',
         'eight'],
 'PART': ["n't", 'to', 'not'],
 'PRON': ['nothing',
          'the',
          'my',
          'this',
          'something',
          'they',
          'whom',
          'nobody',
          'her',
          'those',
          'me',
          'he',
          'themselves',
          'us',
          'an',
          'anything',
          'his',
          'i',
          'you',
          'which',
          'him',
          'all',
          'we',
          'them',
          'any',
          'who',
          'everyone',
          'these',
          'someone',
          'some',
          'himself',
          'whoever',
          'what',
          'each',
          'yourself',
          'mine',
          'everything',
          'our',
          'itself',
          'anyone',
          'herself',
          'your',
          'its',
          'every',
          'it',
          'their',
          'both',
          'ourselves',
          'that',
          'another',
          'whatever',
          'she',
          'myself',
          'a'],
 'PUNCT': ['‘ll', '’ve', '‘ve', '‘d', '’m', '‘m', '‘re'],
 'SCONJ': ['where',
           'wherever',
           'unless',
           'wherein',
           'if',
           'how',
           'though',
           'why',
           'except',
           'whether',
           'while',
           'upon',
           'whereas',
           'besides',
           'when',
           'because',
           'whereby',
           'whenever',
           'since',
           'although'],
 'VERB': ['became',
          'made',
          'hereafter',
          'used',
          'using',
          'did',
          'becomes',
          'seem',
          'do',
          'seems',
          "'d",
          'done',
          'give',
          'keep',
          'say',
          'has',
          'get',
          'become',
          'have',
          'doing',
          'seemed',
          'make',
          'n‘t',
          'put',
          'take',
          'becoming',
          'show',
          "'m",
          "'ve",
          '’s',
          'see',
          'regarding',
          'move',
          'had',
          'seeming',
          'call',
          're',
          'go',
          '’re',
          'does']}
"""



